/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2019-05-19 07:27:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class feedback_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"style.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"feedback.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- header start -->\r\n");
      out.write("<div class=\"topnav\">\r\n");
      out.write("\r\n");
      out.write("  <a class=\"active\" href=\"index.html\">Zoo</a>\r\n");
      out.write("  <a href=\"#buynow\">Buy Now</a>\r\n");
      out.write("  <a href=\"#faq\">FAQ</a>\r\n");
      out.write("  <a href=\"#info\">Info</a>\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("  <div class=\"topnav-right\">\r\n");
      out.write("    <a href=\"#signup\">Sign Up</a>\r\n");
      out.write("    <a href=\"#login\">Login</a>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"navmain\">\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("  <div class=\"column50\">\r\n");
      out.write("    <div class=\"title\">\r\n");
      out.write("\t\tZoo | Online Shopping Store\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"column\">\r\n");
      out.write("   \r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("</div>\r\n");
      out.write("<!-- header end -->\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write(" <div class=\"row \" style=\"margin-top: 50px\"></div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"colomn\">\r\n");
      out.write("\t<h2>FEEDBACK</h2>\r\n");
      out.write("    <p> Please provide your feedback below: </p>\r\n");
      out.write("\t\r\n");
      out.write("\t<form role=\"form\" method=\"post\" id=\"reused_form\" action=\"process.jsp\">\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\t<div class=\"testing\">\r\n");
      out.write("          <label>How do you rate your overall experience?</label>\r\n");
      out.write("          <p>\r\n");
      out.write("\t\t  <label class=\"radio-inline\">\r\n");
      out.write("          <input type=\"radio\" name=\"experience\" id=\"radio_experience\" value=\"bad\">  Bad   </label>\r\n");
      out.write("          <label class=\"radio-inline\"> \r\n");
      out.write("\t\t  <input type=\"radio\" name=\"experience\" id=\"radio_experience\" value=\"average\">  Average </label>\r\n");
      out.write("          <label class=\"radio-inline\">\r\n");
      out.write("          <input type=\"radio\" name=\"experience\" id=\"radio_experience\" value=\"good\"> Good  </label>\r\n");
      out.write("          </p>\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t    <div class=\"row\">\r\n");
      out.write("            <div class=\"para\">\r\n");
      out.write("            <label for=\"comments\"> Comments:</label><br>\r\n");
      out.write("            <textarea class=\"form-control\" type=\"textarea\" name=\"comments\" id=\"comments\" placeholder=\"Your Comments\" maxlength=\"6000\" rows=\"9\"></textarea>\r\n");
      out.write("            </div> </div><br><br>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t <div class=\"row\">\r\n");
      out.write("             <div class=\"write-1\">\r\n");
      out.write("            <label for=\"name\"> Your Name:</label>\r\n");
      out.write("            <input type=\"text\" class=\"form-control\" id=\"name\" name=\"name\" required=\"\">\r\n");
      out.write("            </div><br>\r\n");
      out.write("            <div class=\"write-2\">\r\n");
      out.write("            <label for=\"email\"> Email:</label>\r\n");
      out.write("            <input type=\"email\" class=\"form-control\" id=\"email\" name=\"email\" required=\"\">\r\n");
      out.write("            </div></div><br>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("            <div class=\"send\">\r\n");
      out.write("            <button type=\"submit\" class=\"btn btn-lg btn-warning btn-block\">Post </button>\r\n");
      out.write("\t\t\t</div></div><br><br>\r\n");
      out.write("            \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div id=\"success_message\" style=\"width:100%; height:100%; display:none; \"> \r\n");
      out.write("\t\t\t<h3>Posted your feedback successfully!</h3> </div>\r\n");
      out.write("\t\t\t<div id=\"error_message\" style=\"width:100%; height:100%; display:none; \"> <h3>Error</h3> Sorry there was an error sending your form. </div>\r\n");
      out.write("\t\t\t</div></div></form>\r\n");
      out.write("\t\t\t</div></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--footer-->\r\n");
      out.write("<div class=\"footer\">\r\n");
      out.write("    <div class=\"columnfooter\">\r\n");
      out.write("      <span>\r\n");
      out.write("        <h3>Zoo | Shopping Store</h3>\r\n");
      out.write("      </span>\r\n");
      out.write("      <span>\r\n");
      out.write(" <p>No. 768. <br> Rosemead place,\r\n");
      out.write("                <br> colombo 3.</p>\r\n");
      out.write("       \r\n");
      out.write("      </span>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"columnfooter\">\r\n");
      out.write("\t\t<span>\r\n");
      out.write("\t\t\t<h3>Contact:</h3>\r\n");
      out.write("\t\t</span>\r\n");
      out.write("\t\t<span><p>\r\n");
      out.write("\t\t\t0112 222333 /\r\n");
      out.write("\t\t\t0112 333488<br>\r\n");
      out.write("\t\t\tFax: +94112222333<br>\r\n");
      out.write("\t\t\tEmail: zoo.online@srilanka.com</p>\r\n");
      out.write("\t\t</span>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"columnfooterright\">\r\n");
      out.write("      <span>\r\n");
      out.write("        <i class=\"fab fa-instagram icons\"></i>\r\n");
      out.write("        <i class=\"fab fa-facebook-f icons\"></i>\r\n");
      out.write("        <i class=\"fab fa-twitter icons\"></i>\r\n");
      out.write("      </span>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
